#!/usr/bin/env python3
"""Vendor the Autobahn TestSuite case files into ``python/cases/``.

Downloads a tagged source archive of ``crossbario/autobahn-testsuite``, extracts
the WebSocket case definitions, and copies them into ``python/cases/`` where the
Rust runner imports each one by filename (``caseX_Y_Z`` -> ``CaseX_Y_Z``).

The cases are vendored verbatim except for a small set of Python 2 -> 3 fixups.
"""

from __future__ import annotations

import io
import re
import shutil
import sys
import tarfile
import urllib.request
from pathlib import Path

# The small set of Python 2 -> 3 syntax fixups we need, keyed by source file
# (cases are otherwise vendored verbatim). Ideally we could use the official
# lib2to3, but that is removed in modern Python. String literals are left
# untouched and handled as bytes in the runtime bridges instead.

# py2 `xrange` -> py3 `range`
_XRANGE = (re.compile(r"\bxrange\b"), "range")

# The invalid-UTF-8 *text* vectors in 6.3/6.4 are byte sequences py2 held as
# `str`; under py3 they must be real `bytes` so the driver sends the exact
# (deliberately invalid) octets rather than UTF-8 re-encoding them. Their payload
# literals are pure `\xNN` escapes, so b-prefixing works as-is.
_BYTE_LITERAL = (re.compile(r"(=\s*)('(?:\\x[0-9a-fA-F]{2})+')"), r"\1b\2")

# The 6.5+ UTF-8 sweep (case6_x_x) synthesizes the same kind of invalid-UTF-8
# *text* payloads at import — not literals to b-prefix, so encode the invalid
# ones (isValid False) to their exact octets here. Valid payloads stay `str`
# (sent as UTF-8 text).
_INVALID_UTF8_PAYLOAD = (
    re.compile(r'"PAYLOAD": p\[1\],'),
    '"PAYLOAD": p[1] if p[0] else p[1].encode("latin-1"),',
)

# The case generators synthesize classes with `type(name, (object, Case), ...)`, which
# is an MRO conflict in py3 (object precedes its own subclass).
# Python 3 doesn't need object at all so we remove it.
_MRO_FIX = (re.compile(r"\(object, Case, \)"), r"(Case, )")

# py2 `print` statements -> print() calls.
_PRINT_FIXES = [
    (re.compile(r"^(\s*)print (.+)$", re.M), r"\1print(\2)"),
    (re.compile(r"^(\s*)print$", re.M), r"\1print()"),
]

_FIXUPS: dict[str, list[tuple[re.Pattern[str], str]]] = {
    "case2_10.py": [_XRANGE],
    "case5_16.py": [_XRANGE],
    "case5_17.py": [_XRANGE],
    "case6_3_1.py": [_BYTE_LITERAL],
    "case6_4_1.py": [_BYTE_LITERAL],
    "case6_x_x.py": [*_PRINT_FIXES, _MRO_FIX, _XRANGE, _INVALID_UTF8_PAYLOAD],
    "case7_7_X.py": [_MRO_FIX],
    "case7_9_X.py": [_MRO_FIX],
    "case9_7_X.py": [_MRO_FIX],
    # case10_1_1 compares a frame *count* against len(payload)/autoFragmentSize,
    # requiring int division.
    "case10_1_1.py": [
        (
            re.compile(r"len\(self\.payload\) / self\.p\.autoFragmentSize"),
            "len(self.payload) // self.p.autoFragmentSize",
        ),
    ],
    "case12_x_x.py": [_MRO_FIX],
}


def _apply_fixups(text: str, name: str) -> str:
    for pattern, replacement in _FIXUPS.get(name, []):
        text = pattern.sub(replacement, text)
    return text


def _write_index(static_modules: list[str]) -> None:
    """Emit kosoku/cases/__init__.py: the manifest the runner imports."""
    body = [
        '"""Auto-generated by scripts/generate.py — do not edit.',
        "",
        "Index of the vendored Autobahn TestSuite cases. Importing this package",
        "builds the index, so the runner reads `kosoku.cases.CASES` (id -> case",
        "class) with no filesystem access. `GROUPS` (major -> minor -> [ids]) is",
        "for report rendering; per-case text is on each class (DESCRIPTION /",
        "EXPECTATION).",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from kosoku._caseindex import build_index, initialize_shims",
        "",
        "#: Static case modules (one Case class each), in case-id order.",
        "STATIC_MODULES = [",
        *[f'    "{m}",' for m in static_modules],
        "]",
        "",
        "#: Generator templates and the attribute holding their synthesized classes.",
        "GENERATORS = [",
        *[f'    ("{mod}", "{attr}"),' for mod, attr in _GENERATORS],
        "]",
        "",
        "initialize_shims()",
        "CASES, GROUPS = build_index(STATIC_MODULES, GENERATORS)",
        "",
    ]
    (CASES_DIR / "__init__.py").write_text("\n".join(body), encoding="utf-8")


DEFAULT_TAG = "v25.10.1"
REPO = "crossbario/autobahn-testsuite"
REPO_ROOT = Path(__file__).resolve().parent.parent
# We use the target dir for caching artifacts
TARGET_DIR = REPO_ROOT / "target"
CASES_DIR = REPO_ROOT / "python" / "kosoku" / "cases"
TESTDATA_DIR = (
    REPO_ROOT / "python" / "kosoku" / "shim" / "autobahntestsuite" / "testdata"
)
REPORT_ASSETS = REPO_ROOT / "python" / "kosoku" / "_report_assets.py"

_GENERATORS = [
    ("case6_x_x", "Case6_X_X"),  # 6.5+ UTF-8 sweep
    ("case7_7_X", "Case7_7_X"),  # valid close codes
    ("case7_9_X", "Case7_9_X"),  # invalid close codes
    ("case9_7_X", "Case9_7_X"),  # text RTT/latency
    ("case9_7_X", "Case9_8_X"),  # binary RTT/latency
    ("case12_x_x", "Case12_X_X"),  # permessage-deflate (payloads)
    ("case12_x_x", "Case13_X_X"),  # permessage-deflate (parameters)
]
_RUNNABLE_RE = re.compile(r"^case\d+(?:_\d+)+$")

# Files to copy out of the upstream ``case/`` package
_CASE_RE = re.compile(r"case\d.*\.py$")

# Cases to skip entirely. ``case9_9_1`` is disabled in Autobahn's own registry
# (``#Cases += [Case9_9_1]``) and is the sole case that imports Twisted, so we
# do not vendor it.
_EXCLUDE = {"case9_9_1.py"}


def _archive_url(tag: str) -> str:
    return f"https://github.com/{REPO}/archive/refs/tags/{tag}.tar.gz"


def _fetch_source(tag: str) -> Path:
    dest = TARGET_DIR / f"autobahn-testsuite-{tag}"
    if next(dest.glob("**/case/case.py"), None) is not None:
        print(f"using cached source at {dest}")
        return dest

    url = _archive_url(tag)
    print(f"fetching {url}")
    with urllib.request.urlopen(url) as resp:  # noqa: S310 - fixed github host
        data = resp.read()
    print(f"  {len(data):,} bytes")

    dest.mkdir(parents=True, exist_ok=True)
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tar:
        tar.extractall(dest, filter="data")
    return dest


def _find_case_dir(root: Path) -> Path:
    matches = sorted(root.glob("**/case/case.py"))
    if not matches:
        raise SystemExit(f"could not find a case/case.py under {root}")
    return matches[0].parent


def _write_report_assets(case_dir: Path, tag: str) -> None:
    report_src = (case_dir.parent / "report.py").read_text(encoding="utf-8")
    caseinit_src = (case_dir / "__init__.py").read_text(encoding="utf-8")

    def grab(src: str, pattern: str, name: str) -> str:
        match = re.search(pattern, src, re.DOTALL)
        if not match:
            raise SystemExit(f"could not extract {name} for report assets")
        return match.group(1)

    spans = [
        grab(report_src, rf'({const} = """.*?""")', const)
        for const in (
            "CSS_COMMON",
            "CSS_MASTER_REPORT",
            "CSS_DETAIL_REPORT",
            "JS_MASTER_REPORT",
        )
    ]
    spans.append(grab(caseinit_src, r"(CaseCategories = \{.*?\})", "CaseCategories"))
    spans.append(
        grab(caseinit_src, r"(CaseSubCategories = \{.*?\})", "CaseSubCategories")
    )

    header = (
        '"""Auto-generated by scripts/generate.py — do not edit.\n\n'
        "CSS/JS report assets and the base case category/subcategory names,\n"
        f"vendored from Autobahn TestSuite {REPO}@{tag} (report.py + case/__init__.py).\n"
        '"""\n\n'
    )
    REPORT_ASSETS.write_text(header + "\n\n".join(spans) + "\n", encoding="utf-8")


def main() -> int:
    tag = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_TAG
    case_dir = _find_case_dir(_fetch_source(tag))

    sources = [case_dir / "case.py"]
    sources += sorted(
        p
        for p in case_dir.iterdir()
        if _CASE_RE.match(p.name) and p.name not in _EXCLUDE
    )

    CASES_DIR.mkdir(parents=True, exist_ok=True)
    for stale in CASES_DIR.glob("*.py"):
        stale.unlink()
    shutil.rmtree(CASES_DIR / "__pycache__", ignore_errors=True)

    copied = []
    for src in sources:
        text = src.read_text(encoding="utf-8")
        fixed = _apply_fixups(text, src.name)
        (CASES_DIR / src.name).write_text(fixed, encoding="utf-8")
        copied.append(src.name)

    testdata_src = case_dir.parent / "testdata"
    TESTDATA_DIR.mkdir(parents=True, exist_ok=True)
    for stale in TESTDATA_DIR.iterdir():
        if stale.is_file():
            stale.unlink()
    data_files = [p for p in sorted(testdata_src.iterdir()) if p.is_file()]
    for src in data_files:
        shutil.copy2(src, TESTDATA_DIR / src.name)

    _write_report_assets(case_dir, tag)

    print(f"vendored {len(copied)} case files from {REPO}@{tag} into {CASES_DIR}")
    print(f"vendored {len(data_files)} testdata files into {TESTDATA_DIR}")
    print(f"vendored HTML report assets into {REPORT_ASSETS}")

    # Surface py2-era files that won't import under Python 3.
    unparseable = []
    for path in sorted(CASES_DIR.glob("*.py")):
        try:
            compile(path.read_text(encoding="utf-8"), str(path), "exec")
        except SyntaxError as exc:
            unparseable.append((path.name, f"line {exc.lineno}: {exc.msg}"))

    if unparseable:
        print(f"\n{len(unparseable)} file(s) do not parse as Python 3 (need fixups):")
        for name, why in unparseable:
            print(f"  {name}: {why}")
    else:
        print("all vendored files parse as Python 3")

    static_modules = sorted(
        (name[:-3] for name in copied if _RUNNABLE_RE.match(name[:-3])),
        key=lambda m: [int(p) for p in m.removeprefix("case").split("_")],
    )
    _write_index(static_modules)
    print(
        f"wrote {CASES_DIR / '__init__.py'} indexing {len(static_modules)} static modules"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
